line_global=Sekcja globalna,11
trans_webmin=T³umaczenie:,1,1-Webmina,0-Usermina
trans_working_path=¦cie¿ka robocza,7
line_email=Poczta elektroniczna,11
trans_team_email=Adres grupy t³umaczenia Webmina<br> (Domy¶lnie: <code>translations@webmin.com</code>),0
trans_email=Twój adres e-mail,0
trans_name=Imiê i nazwisko,0
trans_use_mailboxes=U¿yj ustawieñ poczty u¿ytkownika do wysy³ania poczty elektronicznej,1,1-Tak,0-Nie
trans_smtp=Host SMTP (<small>je¶li nie chcesz u¿yæ ustawieñ poczty u¿ytkownika</small>),0
line_auth=Autoryzacja SMTP (<small>je¶li nie chcesz u¿yæ ustawieñ poczty u¿ytkownika</small>),11
trans_smtp_method=Metoda,4,LOGIN-LOGIN,PLAIN-PLAIN,CRAM-MD5-CRAM-MD5,NTLM-NTLM
trans_smtp_user=U¿ytkownik,0
trans_smtp_pwd=Has³o,0
